import 'dart:io';

import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:pharmacy_saas/core/data/app_database.dart';
import 'package:pharmacy_saas/core/data/tables/expense_category.dart';
import 'package:pharmacy_saas/core/data/tables/ledger_entry_type.dart';
import 'package:pharmacy_saas/core/data/tables/stock_movement_type.dart';

import '../../support/helpers.dart';

/// The v7 → v8 migration rehearsal (AGENTS.md standing rule §8, PLANS/13
/// §6.3) — the third execution of the rehearsal standard, template kept
/// consistent with the v5 → v6 and v6 → v7 runs.
///
/// Fixture construction mirrors a real v7 install as closely as drift
/// allows: the schema is generated by drift itself (no duplicated SQL),
/// seeded with all five entry types, two expense categories, a mix of
/// stamped/unsynced rows, a quarantine row, identity/catalog rows, and
/// stock movements of all four types — then the v8-only column is dropped
/// and `user_version` rolled back to 7 so the reopen runs the REAL
/// `onUpgrade(7 → 8)` path. Integrity and the new column's default are
/// asserted across the migration.
void main() {
  late Directory tempDir;
  late File dbFile;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('pharmacy_v8_migration');
    dbFile = File('${tempDir.path}/pharmacy.sqlite');
  });

  tearDown(() {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  Future<AppDatabase> open() async {
    final db = AppDatabase(NativeDatabase(dbFile));
    await db.customSelect('SELECT 1').getSingle();
    return db;
  }

  Future<int> seedEntry(
    AppDatabase db,
    int pharmacyId, {
    required LedgerEntryType type,
    int amountMinor = 1000,
    int? productId,
    int? supplierId,
    int? customerId,
    int? profileId,
    ExpenseCategory? category,
    DateTime? syncedAt,
  }) {
    return db
        .into(db.ledgerEntries)
        .insert(
          LedgerEntriesCompanion.insert(
            pharmacyId: pharmacyId,
            type: type,
            amountMinor: amountMinor,
            productId: Value(productId),
            supplierId: Value(supplierId),
            customerId: Value(customerId),
            profileId: Value(profileId),
            category: Value(category),
            occurredAt: DateTime(2026, 8, 1, 10),
            syncedAt: Value(syncedAt),
          ),
        );
  }

  Future<void> seedMovement(
    AppDatabase db,
    int pharmacyId,
    int productId, {
    required StockMovementType type,
    required int quantity,
    int? profileId,
    String? note,
  }) {
    return db.into(db.stockMovements).insert(
          StockMovementsCompanion.insert(
            pharmacyId: pharmacyId,
            productId: productId,
            type: type,
            quantity: quantity,
            occurredAt: DateTime(2026, 8, 1, 10),
            profileId: Value(profileId),
            note: Value(note),
          ),
        );
  }

  test(
    'v7 fixture (all entry types, categories, mixed synced/unsynced, '
    'quarantine, four stock movement types, identity rows) migrates to '
    'v8 intact with auto_deduct_stock defaulted ON',
    () async {
      final v7 = await open();
      final pharmacyId = await seedPharmacy(v7);
      final profileId = await seedProfile(v7, pharmacyId);
      final productId = await seedProduct(v7, pharmacyId);
      final supplierId = await seedSupplier(v7, pharmacyId);
      final customerId = await seedCustomer(v7, pharmacyId);
      final stampedAt = DateTime.utc(2026, 8, 4, 9, 30);

      final saleId = await seedEntry(
        v7,
        pharmacyId,
        type: LedgerEntryType.sale,
        amountMinor: 1050,
        productId: productId,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final rentExpenseId = await seedEntry(
        v7,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 500,
        category: ExpenseCategory.rent,
        profileId: profileId,
      );
      final drawExpenseId = await seedEntry(
        v7,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 300,
        category: ExpenseCategory.ownerDraw,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final supplierDebtId = await seedEntry(
        v7,
        pharmacyId,
        type: LedgerEntryType.supplierDebt,
        amountMinor: 2500,
        supplierId: supplierId,
      );
      final customerDebtId = await seedEntry(
        v7,
        pharmacyId,
        type: LedgerEntryType.customerDebt,
        amountMinor: 1500,
        customerId: customerId,
        syncedAt: stampedAt,
      );
      final repaymentId = await seedEntry(
        v7,
        pharmacyId,
        type: LedgerEntryType.debtRepayment,
        amountMinor: 200,
        supplierId: supplierId,
      );

      // A quarantined entry (sync bookkeeping row) must survive too.
      await v7.into(v7.syncQuarantineEntries).insert(
            SyncQuarantineEntriesCompanion.insert(
              pharmacyId: pharmacyId,
              entryId: saleId,
              code: '23503',
              message: const Value('Key (product_id)=(1) is not present'),
              quarantinedAt: stampedAt,
            ),
          );

      // All four stock movement types, attributed and annotated, mixed
      // across two products so the surviving rows exercise the full type
      // set and per-product grouping.
      final productId2 = await seedProduct(v7, pharmacyId);
      await seedMovement(
        v7,
        pharmacyId,
        productId,
        type: StockMovementType.initial,
        quantity: 30,
        profileId: profileId,
      );
      await seedMovement(
        v7,
        pharmacyId,
        productId,
        type: StockMovementType.stockIn,
        quantity: 10,
        profileId: profileId,
        note: 'restock',
      );
      await seedMovement(
        v7,
        pharmacyId,
        productId,
        type: StockMovementType.stockOut,
        quantity: -5,
        profileId: profileId,
        note: 'sale',
      );
      await seedMovement(
        v7,
        pharmacyId,
        productId2,
        type: StockMovementType.adjustment,
        quantity: -2,
      );

      // Roll the fixture back to the v7 shape: drop the v8-only column and
      // rewind user_version so the reopen exercises the real 7 → 8 step.
      await v7.customStatement(
        'ALTER TABLE pharmacies DROP COLUMN auto_deduct_stock',
      );
      await v7.customStatement('PRAGMA user_version = 7');
      await v7.close();

      final db = await open();

      // Schema version advanced.
      final version = await db.customSelect('PRAGMA user_version').getSingle();
      expect(version.read<int>('user_version'), 8);

      // The new column exists and defaults ON for the pre-existing row —
      // existing pharmacies must not be silently switched off.
      final pharmacy = (await db.select(db.pharmacies).get()).single;
      expect(pharmacy.autoDeductStock, isTrue);

      // Identity rows survived.
      expect(await db.select(db.pharmacies).get(), hasLength(1));
      expect(await db.select(db.userProfiles).get(), hasLength(1));
      expect(await db.select(db.products).get(), hasLength(2));
      expect(await db.select(db.suppliers).get(), hasLength(1));
      expect(await db.select(db.customers).get(), hasLength(1));

      // The quarantine row survived intact.
      final quarantine = await db.select(db.syncQuarantineEntries).get();
      expect(quarantine, hasLength(1));
      expect(quarantine.single.entryId, saleId);
      expect(quarantine.single.code, '23503');
      expect(quarantine.single.quarantinedAt.toUtc(), stampedAt);

      // Every movement survived with type, quantity, attribution, and
      // note intact — the migration must not touch the movement ledger.
      final movements = await db.select(db.stockMovements).get();
      expect(movements, hasLength(4));
      final byType = {for (final m in movements) m.type: m};
      expect(byType[StockMovementType.initial]!.quantity, 30);
      expect(byType[StockMovementType.initial]!.profileId, profileId);
      expect(byType[StockMovementType.stockIn]!.quantity, 10);
      expect(byType[StockMovementType.stockIn]!.note, 'restock');
      expect(byType[StockMovementType.stockOut]!.quantity, -5);
      expect(byType[StockMovementType.stockOut]!.profileId, profileId);
      expect(byType[StockMovementType.adjustment]!.quantity, -2);
      expect(byType[StockMovementType.adjustment]!.profileId, isNull);

      // Ledger variety intact (existing assertions from the v6→v7 run).
      final rows = await (db.select(db.ledgerEntries)
            ..where((t) => t.pharmacyId.equals(pharmacyId)))
          .get();
      final byId = {for (final r in rows) r.id: r};
      expect(byId, hasLength(6));

      final sale = byId[saleId]!;
      expect(sale.type, LedgerEntryType.sale);
      expect(sale.amountMinor, 1050);
      expect(sale.productId, productId);
      expect(sale.profileId, profileId);
      expect(sale.syncedAt?.toUtc(), stampedAt);

      final rent = byId[rentExpenseId]!;
      expect(rent.type, LedgerEntryType.expense);
      expect(rent.category, ExpenseCategory.rent);
      expect(rent.syncedAt, isNull);

      final draw = byId[drawExpenseId]!;
      expect(draw.type, LedgerEntryType.expense);
      expect(draw.category, ExpenseCategory.ownerDraw);
      expect(draw.syncedAt?.toUtc(), stampedAt);

      final supplierDebt = byId[supplierDebtId]!;
      expect(supplierDebt.type, LedgerEntryType.supplierDebt);
      expect(supplierDebt.supplierId, supplierId);
      expect(supplierDebt.syncedAt, isNull);

      final customerDebt = byId[customerDebtId]!;
      expect(customerDebt.type, LedgerEntryType.customerDebt);
      expect(customerDebt.customerId, customerId);
      expect(customerDebt.syncedAt?.toUtc(), stampedAt);

      final repayment = byId[repaymentId]!;
      expect(repayment.type, LedgerEntryType.debtRepayment);
      expect(repayment.supplierId, supplierId);
      expect(repayment.syncedAt, isNull);

      // Unsynced rows still drive staleness after migration.
      expect(
        await db.select(db.ledgerEntries).get().then(
              (all) => all.where((t) => t.syncedAt == null).length,
            ),
        3,
      );

      // A fresh pharmacy created post-migration also defaults to ON.
      final freshPharmacyId = await seedPharmacy(db);
      final fresh = (await db.select(db.pharmacies)
              ..where((t) => t.id.equals(freshPharmacyId)))
          .getSingle();
      expect((await fresh).autoDeductStock, isTrue);

      await db.close();
    },
  );
}