import 'dart:io';

import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:pharmacy_saas/core/data/app_database.dart';
import 'package:pharmacy_saas/core/data/tables/expense_category.dart';
import 'package:pharmacy_saas/core/data/tables/ledger_entry_type.dart';
import 'package:pharmacy_saas/core/data/tables/stock_movement_type.dart';

import '../../support/helpers.dart';

/// The v8 → v9 migration rehearsal (AGENTS.md standing rule §8, PLANS/14
/// §6.3) — the fourth execution of the rehearsal standard, template kept
/// consistent with the v5 → v6, v6 → v7, and v7 → v8 runs.
///
/// Fixture construction mirrors a real v8 install as closely as drift
/// allows: the schema is generated by drift itself (no duplicated SQL),
/// seeded with all five entry types, two expense categories, a mix of
/// stamped/unsynced rows, a quarantine row, identity/catalog rows, and
/// stock movements of all four types — then the v9-only column is dropped
/// (one product was holding a threshold at the pre-rollback shape — real
/// v8 data can never carry one) and `user_version` rolled back to 8 so
/// the reopen runs the REAL `onUpgrade(8 → 9)` path. Integrity across the
/// migration is asserted, the new column reads NULL for every pre-existing
/// row (real v8 data has no thresholds), and the column's writability is
/// proven by setting a threshold and surviving a reopen.
void main() {
  late Directory tempDir;
  late File dbFile;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('pharmacy_v9_migration');
    dbFile = File('${tempDir.path}/pharmacy.sqlite');
  });

  tearDown(() {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  Future<AppDatabase> open() async {
    final db = AppDatabase(NativeDatabase(dbFile));
    await db.customSelect('SELECT 1').getSingle();
    return db;
  }

  Future<int> seedEntry(
    AppDatabase db,
    int pharmacyId, {
    required LedgerEntryType type,
    int amountMinor = 1000,
    int? productId,
    int? supplierId,
    int? customerId,
    int? profileId,
    ExpenseCategory? category,
    DateTime? syncedAt,
  }) {
    return db
        .into(db.ledgerEntries)
        .insert(
          LedgerEntriesCompanion.insert(
            pharmacyId: pharmacyId,
            type: type,
            amountMinor: amountMinor,
            productId: Value(productId),
            supplierId: Value(supplierId),
            customerId: Value(customerId),
            profileId: Value(profileId),
            category: Value(category),
            occurredAt: DateTime(2026, 8, 1, 10),
            syncedAt: Value(syncedAt),
          ),
        );
  }

  Future<int> seedMovement(
    AppDatabase db,
    int pharmacyId,
    int productId, {
    required StockMovementType type,
    required int quantity,
    int? profileId,
    String? note,
  }) {
    return db.into(db.stockMovements).insert(
          StockMovementsCompanion.insert(
            pharmacyId: pharmacyId,
            productId: productId,
            type: type,
            quantity: quantity,
            occurredAt: DateTime(2026, 8, 1, 10),
            profileId: Value(profileId),
            note: Value(note),
          ),
        );
  }

  test(
    'v8 fixture (all entry types, categories, mixed synced/unsynced, '
    'quarantine, four stock movement types, identity rows) migrates to '
    'v9 intact with low_stock_threshold NULL for pre-existing rows',
    () async {
      final v8 = await open();
      final pharmacyId = await seedPharmacy(v8);
      final profileId = await seedProfile(v8, pharmacyId);
      // One product holds a threshold at the pre-rollback v9 shape; one
      // never does. After the rollback both are plain v8 rows — real v8
      // installs cannot carry threshold data, so both must read NULL.
      final productId = await seedProduct(v8, pharmacyId);
      await (v8.update(v8.products)..where((t) => t.id.equals(productId)))
          .write(const ProductsCompanion(lowStockThreshold: Value(10)));
      final productId2 = await seedProduct(v8, pharmacyId);
      final supplierId = await seedSupplier(v8, pharmacyId);
      final customerId = await seedCustomer(v8, pharmacyId);
      final stampedAt = DateTime.utc(2026, 8, 4, 9, 30);

      final saleId = await seedEntry(
        v8,
        pharmacyId,
        type: LedgerEntryType.sale,
        amountMinor: 1050,
        productId: productId,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final rentExpenseId = await seedEntry(
        v8,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 500,
        category: ExpenseCategory.rent,
        profileId: profileId,
      );
      final drawExpenseId = await seedEntry(
        v8,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 300,
        category: ExpenseCategory.ownerDraw,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final supplierDebtId = await seedEntry(
        v8,
        pharmacyId,
        type: LedgerEntryType.supplierDebt,
        amountMinor: 2500,
        supplierId: supplierId,
      );
      final customerDebtId = await seedEntry(
        v8,
        pharmacyId,
        type: LedgerEntryType.customerDebt,
        amountMinor: 1500,
        customerId: customerId,
        syncedAt: stampedAt,
      );
      final repaymentId = await seedEntry(
        v8,
        pharmacyId,
        type: LedgerEntryType.debtRepayment,
        amountMinor: 200,
        supplierId: supplierId,
      );

      // A quarantined entry (sync bookkeeping row) must survive too.
      await v8.into(v8.syncQuarantineEntries).insert(
            SyncQuarantineEntriesCompanion.insert(
              pharmacyId: pharmacyId,
              entryId: saleId,
              code: '23503',
              message: const Value('Key (product_id)=(1) is not present'),
              quarantinedAt: stampedAt,
            ),
          );

      // All four stock movement types, attributed and annotated, mixed
      // across two products so the surviving rows exercise the full type
      // set and per-product grouping.
      await seedMovement(
        v8,
        pharmacyId,
        productId,
        type: StockMovementType.initial,
        quantity: 30,
        profileId: profileId,
      );
      await seedMovement(
        v8,
        pharmacyId,
        productId,
        type: StockMovementType.stockIn,
        quantity: 10,
        profileId: profileId,
        note: 'restock',
      );
      await seedMovement(
        v8,
        pharmacyId,
        productId,
        type: StockMovementType.stockOut,
        quantity: -5,
        profileId: profileId,
        note: 'sale',
      );
      await seedMovement(
        v8,
        pharmacyId,
        productId2,
        type: StockMovementType.adjustment,
        quantity: -2,
      );

      // Roll the fixture back to the v8 shape: drop the v9-only column and
      // rewind user_version so the reopen exercises the real 8 → 9 step.
      await v8.customStatement(
        'ALTER TABLE products DROP COLUMN low_stock_threshold',
      );
      await v8.customStatement('PRAGMA user_version = 8');
      await v8.close();

      final db = await open();

      // Schema version advanced.
      final version = await db.customSelect('PRAGMA user_version').getSingle();
      expect(version.read<int>('user_version'), 9);

      // Real v8 data carries no thresholds — every pre-existing product
      // reads NULL, not a default or a crashed value.
      final products = await db.select(db.products).get();
      expect(products, hasLength(2));
      expect(products.every((p) => p.lowStockThreshold == null), isTrue);

      // Identity rows survived.
      expect(await db.select(db.pharmacies).get(), hasLength(1));
      expect(await db.select(db.userProfiles).get(), hasLength(1));
      expect(await db.select(db.suppliers).get(), hasLength(1));
      expect(await db.select(db.customers).get(), hasLength(1));

      // The quarantine row survived intact.
      final quarantine = await db.select(db.syncQuarantineEntries).get();
      expect(quarantine, hasLength(1));
      expect(quarantine.single.entryId, saleId);
      expect(quarantine.single.code, '23503');
      expect(quarantine.single.quarantinedAt.toUtc(), stampedAt);

      // Every movement survived with type, quantity, attribution, and
      // note intact — the migration must not touch the movement ledger.
      final movements = await db.select(db.stockMovements).get();
      expect(movements, hasLength(4));
      final byType = {for (final m in movements) m.type: m};
      expect(byType[StockMovementType.initial]!.quantity, 30);
      expect(byType[StockMovementType.initial]!.profileId, profileId);
      expect(byType[StockMovementType.stockIn]!.quantity, 10);
      expect(byType[StockMovementType.stockIn]!.note, 'restock');
      expect(byType[StockMovementType.stockOut]!.quantity, -5);
      expect(byType[StockMovementType.stockOut]!.profileId, profileId);
      expect(byType[StockMovementType.adjustment]!.quantity, -2);
      expect(byType[StockMovementType.adjustment]!.profileId, isNull);

      // Ledger variety intact (existing assertions from the v6→v7 run).
      final rows = await (db.select(db.ledgerEntries)
            ..where((t) => t.pharmacyId.equals(pharmacyId)))
          .get();
      final byId = {for (final r in rows) r.id: r};
      expect(byId, hasLength(6));

      final sale = byId[saleId]!;
      expect(sale.type, LedgerEntryType.sale);
      expect(sale.amountMinor, 1050);
      expect(sale.productId, productId);
      expect(sale.profileId, profileId);
      expect(sale.syncedAt?.toUtc(), stampedAt);

      final rent = byId[rentExpenseId]!;
      expect(rent.type, LedgerEntryType.expense);
      expect(rent.category, ExpenseCategory.rent);
      expect(rent.syncedAt, isNull);

      final draw = byId[drawExpenseId]!;
      expect(draw.type, LedgerEntryType.expense);
      expect(draw.category, ExpenseCategory.ownerDraw);
      expect(draw.syncedAt?.toUtc(), stampedAt);

      final supplierDebt = byId[supplierDebtId]!;
      expect(supplierDebt.type, LedgerEntryType.supplierDebt);
      expect(supplierDebt.supplierId, supplierId);
      expect(supplierDebt.syncedAt, isNull);

      final customerDebt = byId[customerDebtId]!;
      expect(customerDebt.type, LedgerEntryType.customerDebt);
      expect(customerDebt.customerId, customerId);
      expect(customerDebt.syncedAt?.toUtc(), stampedAt);

      final repayment = byId[repaymentId]!;
      expect(repayment.type, LedgerEntryType.debtRepayment);
      expect(repayment.supplierId, supplierId);
      expect(repayment.syncedAt, isNull);

      // Unsynced rows still drive staleness after migration.
      expect(
        await db.select(db.ledgerEntries).get().then(
              (all) => all.where((t) => t.syncedAt == null).length,
            ),
        3,
      );

      // The column is writable and durable: threshold set on a pre-existing
      // row survives a reopen.
      await (db.update(db.products)..where((t) => t.id.equals(productId)))
          .write(const ProductsCompanion(lowStockThreshold: Value(15)));
      // A post-migration product can carry a threshold from birth.
      final freshId = await db.into(db.products).insert(
            ProductsCompanion.insert(
              pharmacyId: pharmacyId,
              name: 'أسبرين 81',
              costMinor: 1200,
              sellMinor: 1500,
              lowStockThreshold: const Value(5),
            ),
          );
      await db.close();

      final reopened = await open();
      final persisted = {
        for (final p in await reopened.select(reopened.products).get())
          p.id: p.lowStockThreshold,
      };
      expect(persisted[productId], 15);
      expect(persisted[productId2], isNull);
      expect(persisted[freshId], 5);
      await reopened.close();
    },
  );
}