import 'dart:io';

import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:pharmacy_saas/core/data/app_database.dart';
import 'package:pharmacy_saas/core/data/tables/expense_category.dart';
import 'package:pharmacy_saas/core/data/tables/ledger_entry_type.dart';

import '../../support/helpers.dart';

/// The v6 → v7 migration rehearsal (AGENTS.md standing rule §8, PLANS/12
/// §8) — the second execution of the rehearsal standard, template kept
/// consistent with the v5 → v6 run.
///
/// Fixture construction mirrors a real v6 install as closely as drift
/// allows: the schema is generated by drift itself (no duplicated SQL),
/// seeded with all five entry types, two expense categories, a mix of
/// stamped/unsynced rows, a quarantine row, and the identity/catalog
/// rows — then the v7-only table is dropped and `user_version` rolled
/// back to 6 so the reopen runs the REAL `onUpgrade(6 → 7)` path.
/// Integrity is asserted across the migration.
void main() {
  late Directory tempDir;
  late File dbFile;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('pharmacy_v7_migration');
    dbFile = File('${tempDir.path}/pharmacy.sqlite');
  });

  tearDown(() {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  Future<AppDatabase> open() async {
    final db = AppDatabase(NativeDatabase(dbFile));
    await db.customSelect('SELECT 1').getSingle();
    return db;
  }

  Future<int> seedEntry(
    AppDatabase db,
    int pharmacyId, {
    required LedgerEntryType type,
    int amountMinor = 1000,
    int? productId,
    int? supplierId,
    int? customerId,
    int? profileId,
    ExpenseCategory? category,
    DateTime? syncedAt,
  }) {
    return db
        .into(db.ledgerEntries)
        .insert(
          LedgerEntriesCompanion.insert(
            pharmacyId: pharmacyId,
            type: type,
            amountMinor: amountMinor,
            productId: Value(productId),
            supplierId: Value(supplierId),
            customerId: Value(customerId),
            profileId: Value(profileId),
            category: Value(category),
            occurredAt: DateTime(2026, 8, 1, 10),
            syncedAt: Value(syncedAt),
          ),
        );
  }

  test(
    'v6 fixture (all five entry types, categories, mixed synced/unsynced, '
    'quarantine, identity rows) migrates to v7 intact',
    () async {
      final v6 = await open();
      final pharmacyId = await seedPharmacy(v6);
      final profileId = await seedProfile(v6, pharmacyId);
      final productId = await seedProduct(v6, pharmacyId);
      final supplierId = await seedSupplier(v6, pharmacyId);
      final customerId = await seedCustomer(v6, pharmacyId);
      final stampedAt = DateTime.utc(2026, 8, 4, 9, 30);

      final saleId = await seedEntry(
        v6,
        pharmacyId,
        type: LedgerEntryType.sale,
        amountMinor: 1050,
        productId: productId,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final rentExpenseId = await seedEntry(
        v6,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 500,
        category: ExpenseCategory.rent,
        profileId: profileId,
      );
      final drawExpenseId = await seedEntry(
        v6,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 300,
        category: ExpenseCategory.ownerDraw,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final supplierDebtId = await seedEntry(
        v6,
        pharmacyId,
        type: LedgerEntryType.supplierDebt,
        amountMinor: 2500,
        supplierId: supplierId,
      );
      final customerDebtId = await seedEntry(
        v6,
        pharmacyId,
        type: LedgerEntryType.customerDebt,
        amountMinor: 1500,
        customerId: customerId,
        syncedAt: stampedAt,
      );
      final repaymentId = await seedEntry(
        v6,
        pharmacyId,
        type: LedgerEntryType.debtRepayment,
        amountMinor: 200,
        supplierId: supplierId,
      );

      // A quarantined entry (sync bookkeeping row) must survive too.
      await v6.into(v6.syncQuarantineEntries).insert(
            SyncQuarantineEntriesCompanion.insert(
              pharmacyId: pharmacyId,
              entryId: saleId,
              code: '23503',
              message: const Value('Key (product_id)=(1) is not present'),
              quarantinedAt: stampedAt,
            ),
          );

      // Roll the fixture back to the v6 shape: drop the v7-only table and
      // rewind user_version so the reopen exercises the real 6 → 7 step.
      await v6.customStatement('DROP TABLE stock_movements');
      // The v8-only column must also go — a real v6 install predates it,
      // and the reopen would otherwise collide with the real onUpgrade
      // chain's from<8 addColumn step.
      await v6.customStatement(
        'ALTER TABLE pharmacies DROP COLUMN auto_deduct_stock',
      );
      // The v9-only column must go too — same reason (reopen ladder's
      // from<9 addColumn step; PLANS/14).
      await v6.customStatement(
        'ALTER TABLE products DROP COLUMN low_stock_threshold',
      );
      await v6.customStatement('PRAGMA user_version = 6');
      await v6.close();

      final db = await open();

      // Schema version advanced to the shipping head (v9 as of PLANS/14).
      final version = await db.customSelect('PRAGMA user_version').getSingle();
      expect(version.read<int>('user_version'), 9);

      // The stock movements table exists and is empty.
      expect(await db.select(db.stockMovements).get(), isEmpty);

      // Identity rows survived.
      expect(await db.select(db.pharmacies).get(), hasLength(1));
      expect(await db.select(db.userProfiles).get(), hasLength(1));
      expect(await db.select(db.products).get(), hasLength(1));
      expect(await db.select(db.suppliers).get(), hasLength(1));
      expect(await db.select(db.customers).get(), hasLength(1));

      // The quarantine row survived intact.
      final quarantine = await db.select(db.syncQuarantineEntries).get();
      expect(quarantine, hasLength(1));
      expect(quarantine.single.entryId, saleId);
      expect(quarantine.single.code, '23503');
      expect(quarantine.single.quarantinedAt.toUtc(), stampedAt);

      // Every ledger row survived with type, category, amount, and the
      // sync flag intact — the migration must not touch ledger data.
      final rows = await (db.select(db.ledgerEntries)
            ..where((t) => t.pharmacyId.equals(pharmacyId)))
          .get();
      final byId = {for (final r in rows) r.id: r};
      expect(byId, hasLength(6));

      final sale = byId[saleId]!;
      expect(sale.type, LedgerEntryType.sale);
      expect(sale.amountMinor, 1050);
      expect(sale.productId, productId);
      expect(sale.profileId, profileId);
      expect(sale.syncedAt?.toUtc(), stampedAt);

      final rent = byId[rentExpenseId]!;
      expect(rent.type, LedgerEntryType.expense);
      expect(rent.category, ExpenseCategory.rent);
      expect(rent.syncedAt, isNull);

      final draw = byId[drawExpenseId]!;
      expect(draw.type, LedgerEntryType.expense);
      expect(draw.category, ExpenseCategory.ownerDraw);
      expect(draw.syncedAt?.toUtc(), stampedAt);

      final supplierDebt = byId[supplierDebtId]!;
      expect(supplierDebt.type, LedgerEntryType.supplierDebt);
      expect(supplierDebt.supplierId, supplierId);
      expect(supplierDebt.syncedAt, isNull);

      final customerDebt = byId[customerDebtId]!;
      expect(customerDebt.type, LedgerEntryType.customerDebt);
      expect(customerDebt.customerId, customerId);
      expect(customerDebt.syncedAt?.toUtc(), stampedAt);

      final repayment = byId[repaymentId]!;
      expect(repayment.type, LedgerEntryType.debtRepayment);
      expect(repayment.supplierId, supplierId);
      expect(repayment.syncedAt, isNull);

      // Unsynced rows still drive staleness after migration.
      expect(
        await db.select(db.ledgerEntries).get().then(
              (all) => all.where((t) => t.syncedAt == null).length,
            ),
        3,
      );

      await db.close();
    },
  );
}