import 'dart:io';

import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:pharmacy_saas/core/data/app_database.dart';
import 'package:pharmacy_saas/core/data/tables/expense_category.dart';
import 'package:pharmacy_saas/core/data/tables/ledger_entry_type.dart';

import '../../support/helpers.dart';

/// The v5 → v6 migration rehearsal (AGENTS.md standing rule §8):
///
/// Fixture construction mirrors a real v5 install as closely as drift
/// allows: the schema is generated by drift itself (no duplicated SQL),
/// seeded with all five entry types, two expense categories, and a mix of
/// stamped/unsynced rows — then the v6-only table is dropped and
/// `user_version` rolled back to 5 so the reopen runs the REAL
/// `onUpgrade(5 → 6)` path. Integrity is asserted across the migration.
///
/// Updated for PLANS/12: the rehearsal's target is the shipping head
/// (v7) — a real v5 install upgrading to the plan-12 build runs the full
/// 5 → 7 ladder, so the fixture now asserts the v6 AND v7 steps both
/// land with every pre-existing row intact.
///
/// This is the first execution of the pre-launch rehearsal standard
/// (staff-review gate rulings Q2); the full rehearsal-on-real-data rule
/// activates at the first migration after pilot devices hold real data.
void main() {
  late Directory tempDir;
  late File dbFile;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('pharmacy_v6_migration');
    dbFile = File('${tempDir.path}/pharmacy.sqlite');
  });

  tearDown(() {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  Future<AppDatabase> open() async {
    final db = AppDatabase(NativeDatabase(dbFile));
    await db.customSelect('SELECT 1').getSingle();
    return db;
  }

  Future<int> seedEntry(
    AppDatabase db,
    int pharmacyId, {
    required LedgerEntryType type,
    int amountMinor = 1000,
    int? productId,
    int? supplierId,
    int? customerId,
    int? profileId,
    ExpenseCategory? category,
    DateTime? syncedAt,
  }) {
    return db
        .into(db.ledgerEntries)
        .insert(
          LedgerEntriesCompanion.insert(
            pharmacyId: pharmacyId,
            type: type,
            amountMinor: amountMinor,
            productId: Value(productId),
            supplierId: Value(supplierId),
            customerId: Value(customerId),
            profileId: Value(profileId),
            category: Value(category),
            occurredAt: DateTime(2026, 8, 1, 10),
            syncedAt: Value(syncedAt),
          ),
        );
  }

  test(
    'v5 fixture (all five entry types, expense categories, mixed '
    'synced/unsynced) migrates to v6 intact',
    () async {
      final v5 = await open();
      final pharmacyId = await seedPharmacy(v5);
      final profileId = await seedProfile(v5, pharmacyId);
      final productId = await seedProduct(v5, pharmacyId);
      final supplierId = await seedSupplier(v5, pharmacyId);
      final customerId = await seedCustomer(v5, pharmacyId);
      final stampedAt = DateTime.utc(2026, 8, 4, 9, 30);

      final saleId = await seedEntry(
        v5,
        pharmacyId,
        type: LedgerEntryType.sale,
        amountMinor: 1050,
        productId: productId,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final rentExpenseId = await seedEntry(
        v5,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 500,
        category: ExpenseCategory.rent,
        profileId: profileId,
      );
      final drawExpenseId = await seedEntry(
        v5,
        pharmacyId,
        type: LedgerEntryType.expense,
        amountMinor: 300,
        category: ExpenseCategory.ownerDraw,
        profileId: profileId,
        syncedAt: stampedAt,
      );
      final supplierDebtId = await seedEntry(
        v5,
        pharmacyId,
        type: LedgerEntryType.supplierDebt,
        amountMinor: 2500,
        supplierId: supplierId,
      );
      final customerDebtId = await seedEntry(
        v5,
        pharmacyId,
        type: LedgerEntryType.customerDebt,
        amountMinor: 1500,
        customerId: customerId,
        syncedAt: stampedAt,
      );
      final repaymentId = await seedEntry(
        v5,
        pharmacyId,
        type: LedgerEntryType.debtRepayment,
        amountMinor: 200,
        supplierId: supplierId,
      );

      // Roll the fixture back to the v5 shape: drop the v6-only table and
      // rewind user_version so the reopen exercises the real 5 → 6 step.
      await v5.customStatement('DROP TABLE sync_quarantine_entries');
      // The v8-only column must also go — a real v5 install predates it,
      // and the reopen would otherwise collide with the real onUpgrade
      // chain's from<8 addColumn step.
      await v5.customStatement(
        'ALTER TABLE pharmacies DROP COLUMN auto_deduct_stock',
      );
      await v5.customStatement('PRAGMA user_version = 5');
      await v5.close();

      final db = await open();

      // Schema version advanced to the shipping head (v8 as of PLANS/13 —
      // the rollback-to-5 restart runs the full real 5 → 8 ladder).
      final version = await db.customSelect('PRAGMA user_version').getSingle();
      expect(version.read<int>('user_version'), 8);

      // The quarantine table exists and is empty.
      expect(await db.select(db.syncQuarantineEntries).get(), isEmpty);

      // The plan-12 stock movements table exists and is empty.
      expect(await db.select(db.stockMovements).get(), isEmpty);

      // Identity rows survived.
      expect(await db.select(db.pharmacies).get(), hasLength(1));
      expect(await db.select(db.userProfiles).get(), hasLength(1));
      expect(await db.select(db.products).get(), hasLength(1));
      expect(await db.select(db.suppliers).get(), hasLength(1));
      expect(await db.select(db.customers).get(), hasLength(1));

      // Every ledger row survived with type, category, amount, and the
      // sync flag intact — the migration must not touch ledger data.
      final rows = await (db.select(db.ledgerEntries)
            ..where((t) => t.pharmacyId.equals(pharmacyId)))
          .get();
      final byId = {for (final r in rows) r.id: r};
      expect(byId, hasLength(6));

      final sale = byId[saleId]!;
      expect(sale.type, LedgerEntryType.sale);
      expect(sale.amountMinor, 1050);
      expect(sale.productId, productId);
      expect(sale.profileId, profileId);
      expect(sale.syncedAt?.toUtc(), stampedAt);

      final rent = byId[rentExpenseId]!;
      expect(rent.type, LedgerEntryType.expense);
      expect(rent.category, ExpenseCategory.rent);
      expect(rent.syncedAt, isNull);

      final draw = byId[drawExpenseId]!;
      expect(draw.type, LedgerEntryType.expense);
      expect(draw.category, ExpenseCategory.ownerDraw);
      expect(draw.syncedAt?.toUtc(), stampedAt);

      final supplierDebt = byId[supplierDebtId]!;
      expect(supplierDebt.type, LedgerEntryType.supplierDebt);
      expect(supplierDebt.supplierId, supplierId);
      expect(supplierDebt.syncedAt, isNull);

      final customerDebt = byId[customerDebtId]!;
      expect(customerDebt.type, LedgerEntryType.customerDebt);
      expect(customerDebt.customerId, customerId);
      expect(customerDebt.syncedAt?.toUtc(), stampedAt);

      final repayment = byId[repaymentId]!;
      expect(repayment.type, LedgerEntryType.debtRepayment);
      expect(repayment.supplierId, supplierId);
      expect(repayment.syncedAt, isNull);

      // Unsynced rows still drive staleness after migration.
      expect(
        await db.select(db.ledgerEntries).get().then(
              (all) => all.where((t) => t.syncedAt == null).length,
            ),
        3,
      );

      await db.close();
    },
  );
}
