-- 0001_pharmacy_schema.sql
-- Remote mirror of the local drift schema (PLANS/03_DATA_AND_SYNC_PLAN.md)
-- plus the device-token write path.
--
-- Security model (DECISIONS.md, SECURITY.md):
--   * RLS is enabled and ALL privileges on these tables are revoked from
--     the anon role. There are NO direct-table policies.
--   * The only anon-accessible surface is two SECURITY DEFINER functions:
--     register_device and push_ledger_entries. They resolve the tenant
--     from the device token hash — client-supplied ids are never trusted.
--   * ledger_entries is append-only on the server too: no update/delete
--     grants exist, and the function only ever inserts.
--
-- Requires Supabase's pre-enabled pgcrypto extension (extensions schema).

create extension if not exists pgcrypto with schema extensions;

-- Tenant root. Created server-side by register_device (register-first-wins
-- on uuid).
create table public.pharmacies (
  id bigint generated by default as identity primary key,
  uuid text not null unique,
  name text not null,
  currency text not null default 'EGP',
  created_at timestamptz not null default now()
);

-- Schema parity with the local user_profiles (not written to in P0).
create table public.user_profiles (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id),
  role text not null,
  display_name text not null
);

create table public.products (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id),
  name text not null,
  cost_minor bigint not null check (cost_minor >= 0),
  sell_minor bigint not null check (sell_minor >= 0),
  expiry_date date,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.suppliers (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.customers (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id),
  name text not null,
  created_at timestamptz not null default now()
);

-- The append-only ledger. The composite primary key (pharmacy_id, id) is
-- load-bearing: local autoincrement ids collide across tenants, so
-- idempotent retries key on the pair, never on `id` alone.
create table public.ledger_entries (
  id bigint not null,
  pharmacy_id bigint not null references public.pharmacies(id),
  type text not null check (type in (
    'sale', 'cash_draw', 'supplier_debt', 'customer_debt', 'debt_repayment'
  )),
  amount_minor bigint not null check (amount_minor >= 0),
  product_id bigint references public.products(id),
  supplier_id bigint references public.suppliers(id),
  customer_id bigint references public.customers(id),
  profile_id bigint references public.user_profiles(id),
  occurred_at timestamptz not null,
  note text,
  synced_at timestamptz,
  primary key (pharmacy_id, id)
);

create index idx_ledger_pharmacy_occurred_at
  on public.ledger_entries (pharmacy_id, occurred_at);
create index idx_ledger_pharmacy_type
  on public.ledger_entries (pharmacy_id, type);

-- Per-install backup credentials. Only the SHA-256 of the token is ever
-- stored; the token itself lives in the device's secure storage.
-- token_hash is the lowercase hex encoding of the digest (text), so the
-- `= extensions.digest(...)` comparisons below need no cast.
create table public.devices (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id),
  token_hash text not null unique,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Lock everything down: RLS on, no anon/authenticated grants on tables.
-- ---------------------------------------------------------------------------
alter table public.pharmacies enable row level security;
alter table public.user_profiles enable row level security;
alter table public.products enable row level security;
alter table public.suppliers enable row level security;
alter table public.customers enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.devices enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public
  revoke all on tables from anon, authenticated;
alter default privileges in schema public
  revoke all on sequences from anon, authenticated;

-- ---------------------------------------------------------------------------
-- register_device: binds a token to a pharmacy. Register-first-wins: a
-- uuid already claimed by another token is refused, so an attacker cannot
-- hijack a tenant that a real device has already registered.
-- ---------------------------------------------------------------------------
create or replace function public.register_device(
  p_token text,
  p_pharmacy_uuid text,
  p_pharmacy_name text,
  p_currency text default 'EGP'
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pharmacy_id bigint;
  v_token_hash text := encode(extensions.digest(p_token, 'sha256'), 'hex');
begin
  if p_token is null or length(p_token) < 16 then
    raise exception 'invalid device token';
  end if;
  if p_pharmacy_uuid is null or length(p_pharmacy_uuid) < 16 then
    raise exception 'invalid pharmacy uuid';
  end if;

  if exists (
    select 1
    from public.devices d
    join public.pharmacies p on p.id = d.pharmacy_id
    where p.uuid = p_pharmacy_uuid
      and d.token_hash <> v_token_hash
  ) then
    raise exception 'pharmacy already registered to another device';
  end if;

  insert into public.pharmacies (uuid, name, currency)
  values (p_pharmacy_uuid, p_pharmacy_name, coalesce(nullif(p_currency, ''), 'EGP'))
  on conflict (uuid) do nothing;

  select id into v_pharmacy_id
  from public.pharmacies where uuid = p_pharmacy_uuid;

  insert into public.devices (pharmacy_id, token_hash)
  values (v_pharmacy_id, v_token_hash)
  on conflict (token_hash) do nothing;

  return v_pharmacy_id;
end $$;

-- ---------------------------------------------------------------------------
-- push_ledger_entries: append-only backup push. The tenant is derived from
-- the token — the payload contains no pharmacy id and cannot override it.
-- Idempotent: retries of the same batch insert nothing (ON CONFLICT).
-- ---------------------------------------------------------------------------
create or replace function public.push_ledger_entries(
  p_token text,
  p_entries jsonb
) returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pharmacy_id bigint;
  v_entry jsonb;
  v_inserted int := 0;
begin
  select d.pharmacy_id into v_pharmacy_id
  from public.devices d
  where d.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex');

  if v_pharmacy_id is null then
    raise exception 'unknown device token';
  end if;
  if p_entries is null or jsonb_typeof(p_entries) <> 'array' then
    raise exception 'p_entries must be a jsonb array';
  end if;

  for v_entry in select * from jsonb_array_elements(p_entries) loop
    if (v_entry ->> 'id') is null then
      raise exception 'entry missing id';
    end if;
    if (v_entry ->> 'type') not in (
      'sale', 'cash_draw', 'supplier_debt', 'customer_debt', 'debt_repayment'
    ) then
      raise exception 'unknown entry type: %', v_entry ->> 'type';
    end if;
    if (v_entry ->> 'amount_minor') is null
       or (v_entry ->> 'amount_minor')::bigint < 0 then
      raise exception 'invalid amount_minor';
    end if;
    if (v_entry ->> 'occurred_at') is null then
      raise exception 'entry missing occurred_at';
    end if;

    insert into public.ledger_entries (
      id, pharmacy_id, type, amount_minor,
      product_id, supplier_id, customer_id, profile_id,
      occurred_at, note
    )
    values (
      (v_entry ->> 'id')::bigint,
      v_pharmacy_id,
      v_entry ->> 'type',
      (v_entry ->> 'amount_minor')::bigint,
      nullif(v_entry ->> 'product_id', '')::bigint,
      nullif(v_entry ->> 'supplier_id', '')::bigint,
      nullif(v_entry ->> 'customer_id', '')::bigint,
      nullif(v_entry ->> 'profile_id', '')::bigint,
      (v_entry ->> 'occurred_at')::timestamptz,
      v_entry ->> 'note'
    )
    on conflict (pharmacy_id, id) do nothing;

    if found then
      v_inserted := v_inserted + 1;
    end if;
  end loop;

  return v_inserted;
end $$;

grant execute on function public.register_device to anon, authenticated;
grant execute on function public.push_ledger_entries to anon, authenticated;
